import { anonymousPro, inter } from "./ui/fonts";
import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = ["About","Trips","Gallery","Log in"]

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${anonymousPro.variable}`}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className="font-inter antialiased bg-[url('/topography.svg')] bg-repeat"
      >
      <Navbar links={links} />
        {children}
      </body>
    </html>
  );
}
