import { anonymousPro, inter } from "./ui/fonts";
import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${anonymousPro.variable}`}>
      <body
        className="font-inter antialiased bg-[url('/topography.svg')] bg-repeat"
      >
        {children}
      </body>
    </html>
  );
}
